name: ci-1-upload

on:
  push:
    branches: [main]
    paths:
        - ".github/workflows/1-upload.yaml"

jobs:
  upload-test-file-1:
    name: Upload file 1 / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Save file
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-file-1st-run-${{ matrix.os }}
          path: test.txt